### ISSUE TITLE
react 16 support.

### ISSUE THREAD

**Issue by XaveScor** [whoisandy/react-rangeslider#91]
Subj

**Comment by tomellwood** [comment]
react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.

**Comment by makamekm** [comment]
I have with it:
```
[2] Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
[2] Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
[2]     in CompanyModify
[2]     in Apollo(CompanyModify)
[2]     in Apollo(Apollo(CompanyModify))
[2]     in Connect(Apollo(Apollo(CompanyModify)))
[2]     in Route
[2]     in withRouter(Connect(Apollo(Apollo(CompanyModify))))
[2]     in div
[2]     in Transition
[2]     in CSSTransition
[2]     in div
[2]     in TransitionGroup
[2]     in Unknown
[2]     in Route
[2]     in withRouter()
[2]     in div
[2]     in Application
[2]     in Connect(Application)
[2]     in Connect(Connect(Application))
[2]     in Route
[2]     in withRouter(Connect(Connect(Application)))
[2]     in Route
[2]     in Switch
[2]     in div
[2]     in Html
[2]     in Connect(Html)
[2]     in Route
[2]     in withRouter(Connect(Html))
[2]     in Router
[2]     in StaticRouter
[2]     in QueryRecyclerProvider
[2]     in ApolloProvider
[2] (node:30274) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: element.type.toLowerCase is not a function
[2] (node:30274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by XaveScor** [comment]
@makamekm How to get this?

**Comment by avdeev** [comment]
Worked correctly with React 16.2 for me
Only with install warning

@whoisandy I can create PR for update peerDependencies?

**Comment by avdeev** [comment]
Related with #87

**Comment by jeff1evesque** [comment]
Got the same thing, with my [`package.json`](https://github.com/jeff1evesque/machine-learning/blob/ec62640e0839ac9feb58b19d8c08a648baa70c44/src/package.json):

```bash
root@trusty64:/home/vagrant# /usr/bin/npm install react-rangeslider@^2.2.0 --no-bin-links
/home/vagrant
├── UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0
└─┬ react-rangeslider@2.2.0
  ├── classnames@2.2.5
  └── resize-observer-polyfill@1.5.0

npm WARN enoent ENOENT: no such file or directory, open '/home/vagrant/package.json'
npm WARN react-rangeslider@2.2.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN vagrant No description
npm WARN vagrant No repository field.
npm WARN vagrant No README data
npm WARN vagrant No license field.
```

**Comment by Saibamen** [comment]
https://github.com/whoisandy/react-rangeslider/pull/142

**Comment by jufemaiz** [comment]
**ahem** bump?

**Comment by aalibasic** [comment]
@whoisandy - any chance this could get merged in?
